name: AutoCommit

on:
  schedule:
    - cron: '0 0 * * *'
  # allows to manually run the job at any time
  workflow_dispatch:
  # run on every push on the master branch
  # push:
  #   branches:
  #     - main

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v3

      - name: Create empty commit
        run: |
          git config --global user.name "JackieDYH"
          git config --global user.email "1824561218@qq.com"
          git commit --allow-empty -m "Daily Commit"
          git push
