name: AutoCommit

on:
  schedule:
    # 中国时间上午11:10 CST（中国标准时间）/ 3:10 UTC（协调世界时）
    # '0 3 * * *' 中国每天上午11点执行 '*/3 * * * *' 没3分钟执行
    - cron: '*/2 * * * *'
  # allows to manually run the job at any time
  workflow_dispatch:
  # run on every push on the master branch
  # push:
  #   branches:
  #     - main

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v3

      - name: Create empty commit
        run: |
          git config --global user.name "JackieDYH"
          git config --global user.email "1824561218@qq.com"
          git commit --allow-empty -m "Daily Commit"
          git push
