name: Snake

on:
  # run automatically every 24 hours 每天0点执行'0 */24 * * *'  每天0，12点执行'0 0,12 * * *'
  schedule:
    - cron: '0 0,12 * * *'

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 步骤1
      # https://github.com/Platane/snk
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        # uses: Platane/snk@v3
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # gif_out_path: ./assets/github-contribution-grid-snake.gif
          # svg_out_path: ./assets/github-contribution-grid-snake.svg
          # svg_out_path_2: ./assets/github-contribution-grid-dark.svg?palette=github-dark

          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          # dist/github-contribution-grid-snake.gif
          # dist/github-contribution-grid-dark.gif?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 步骤1.2 添加信息文件
      - name: Output current time and user information to file
        run: |
          echo "Current Time (China): $(TZ='Asia/Shanghai' date)" > dist/current_time.txt
          echo "RUN_ID: ${{ github.run_id }}" >> dist/current_time.txt
          echo "工作流程运行的序号: ${{ github.run_number }}" >> dist/current_time.txt
          echo "操作的执行者: ${{ github.actor }}" >> dist/current_time.txt
          echo "触发工作流程的事件的名称: ${{ github.event_name }}" >> dist/current_time.txt
          echo "工作流程的仓库的所有者和名称: ${{ github.repository }}" >> dist/current_time.txt
          echo "工作流程的提交的 SHA 值: ${{ github.sha }}" >> dist/current_time.txt
          echo "工作流程的名称: ${{ github.workflow }}" >> dist/current_time.txt
          echo "工作流程的引用名称: ${{ github.ref }}" >> dist/current_time.txt
          echo "工作流程的工作目录路径: ${{ github.workspace }}" >> dist/current_time.txt
          echo "当前操作的名称: ${{ github.action }}" >> dist/current_time.txt
          echo "工作流程的事件的完整负载数据: ${{ JSON.stringify(github.event) }}" >> dist/current_time.txt
          echo "Other information: https://github.com/JackieDYH" >> dist/current_time.txt

      # 步骤2
      # https://github.com/crazy-max/ghaction-github-pages
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        # - name: Add & Commit
        #   uses: EndBug/add-and-commit@v9.1.3
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
          committer: JackieDYH <1824561218@qq.com>
          author: JackieDYH <1824561218@qq.com>
          commit_message: 'Generate Contribution Snake -ID:${{ github.run_id }} -actor:${{ github.actor }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
